# Generated by Django 5.0.2 on 2024-03-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(default='-', verbose_name='Facebook Link')),
                ('instagram', models.URLField(default='-', verbose_name='Instagram Link')),
                ('twitter', models.URLField(default='-', verbose_name='Twitter Link')),
                ('has_resume', models.BooleanField(default=False)),
                ('has_company', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_resume',
        ),
    ]
