# Generated by Django 5.0.2 on 2024-03-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_yourmodelname_remove_user_has_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModelName',
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(default='-', verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_resume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(default='-', verbose_name='Instagram Link'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(default='-', verbose_name='Twitter Link'),
        ),
    ]
