# Generated by Django 5.0.2 on 2024-03-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_yourmodelname_user_facebook_user_has_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter',
        ),
    ]
