# Generated by Django 5.0.2 on 2024-03-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='job_title',
            new_name='baladia',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
