# Generated by Django 5.0.2 on 2024-04-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_remove_job_location_job_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='post/banners/'),
        ),
        migrations.AddField(
            model_name='job',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
        migrations.AddField(
            model_name='job',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
        migrations.AddField(
            model_name='job',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
        migrations.AddField(
            model_name='job',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
